<<<<<<< HEAD
# Generated by Django 2.1.4 on 2019-01-21 11:43
=======
# Generated by Django 2.1.4 on 2019-01-21 11:05
>>>>>>> 4cafb35a766985252f48335475d448f228afea3f

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
