# Generated by Django 2.1.4 on 2019-01-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('choise_1', models.TextField(max_length=200)),
                ('choise_2', models.TextField(max_length=200)),
                ('choise_3', models.TextField(max_length=200)),
                ('choise_4', models.TextField(max_length=200)),
                ('the_choise', models.IntegerField()),
            ],
        ),
    ]
