# Generated by Django 2.1.4 on 2019-01-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_auto_20190121_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentquestion',
            name='q',
            field=models.IntegerField(default=1),
        ),
    ]
