# Generated by Django 2.1.4 on 2019-01-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0004_currentquestion_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_time', models.IntegerField(default=0)),
                ('second_time', models.IntegerField(default=0)),
            ],
        ),
    ]
