# Generated by Django 2.1.4 on 2019-01-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0005_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='i',
            field=models.IntegerField(default=1),
        ),
    ]
